# SPDX-License-Identifier: GPL-3.0-or-later
"""Shared harness for the M2 harmonic validation.

Builds the two descriptions of a Lennard-Jones crystal that M2 compares — a harmonic
reference via ASE finite displacement and Euphonic, and a pDOS via NVE molecular
dynamics through mdins. Both :mod:`tests.test_euphonic` and
``docs/make_validation_figures.py`` import from here, so the figures in
``docs/validation.md`` are generated by the same code the tests assert on rather than by
a second implementation that can quietly drift.

Not a test module: it contains no assertions and pytest collects nothing from it.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
from numpy.typing import NDArray

from mdins.provenance import Provenance
from mdins.spectral import velocity_spectral_density
from mdins.trajectory import VelocityTrajectory

if TYPE_CHECKING:  # pragma: no cover
    from collections.abc import Sequence

    from ase import Atoms

    from mdins.spectral import VelocitySpectralDensity

#: Lennard-Jones argon, in ASE units (eV, Å).
EPSILON = 0.0103
SIGMA = 3.40
CUTOFF = 8.5

TEMPERATURE = 10.0
TIMESTEP_FS = 5.0
DUMP_EVERY = 4
N_FRAMES = 8192

#: Welch segment, giving 0.1 meV against a band about 4 meV wide. Finer would not help:
#: the modes are spaced more closely than this.
SEGMENT_LENGTH = 2048


def lennard_jones():
    """The one potential both routes see.

    Deliberately species-blind — ASE's Lennard-Jones takes a single epsilon and sigma —
    which is what makes the binary crystal below a clean test. Two species in the same
    cell then differ *only* by mass, so any difference between their spectra has exactly
    one cause.
    """
    from ase.calculators.lj import LennardJones

    return LennardJones(epsilon=EPSILON, sigma=SIGMA, rc=CUTOFF, smooth=True)


def equilibrium_lattice_constant() -> float:
    """Relax the FCC lattice constant.

    Computed rather than tabulated: at a lattice constant that is not a stationary point
    the residual forces produce imaginary modes in the reference and a spurious
    low-energy feature in the MD — a mismatch that looks exactly like a bug in the code
    under test.
    """
    from ase.build import bulk
    from scipy.optimize import minimize_scalar

    def energy(a: float) -> float:
        atoms = bulk("Ar", "fcc", a=a)
        atoms.calc = lennard_jones()
        return float(atoms.get_potential_energy())

    return float(minimize_scalar(energy, bracket=(5.0, 5.3, 5.6)).x)


def single_species_cell(lattice_constant: float) -> Atoms:
    """Primitive FCC argon, one atom."""
    from ase.build import bulk

    return bulk("Ar", "fcc", a=lattice_constant)


def binary_cell(lattice_constant: float) -> Atoms:
    """Ordered Ar/Kr on the conventional FCC cell, four atoms.

    The L1₀ arrangement: alternating (001) layers of argon and krypton. Geometrically
    this is the same FCC lattice the single-species tests use and the potential cannot
    tell the two elements apart, so it sits at the same equilibrium and is guaranteed
    mechanically stable. The mass ratio of about 2.1 is the only asymmetry in the
    problem.
    """
    from ase import Atoms

    sites = [(0.0, 0.0, 0.0), (0.5, 0.5, 0.0), (0.0, 0.5, 0.5), (0.5, 0.0, 0.5)]
    return Atoms(
        "Ar2Kr2",
        scaled_positions=sites,
        cell=lattice_constant * np.eye(3),
        pbc=True,
    )


def commensurate_grid(supercell: tuple[int, int, int]) -> NDArray[np.float64]:
    """Every wavevector the supercell can host, and nothing else.

    A supercell under periodic boundary conditions supports exactly the q of the form
    ``(i/n1, j/n2, k/n3)``. Sampling the reference anywhere else adds modes the MD was
    never able to hold, and the comparison then fails for a reason that has nothing to
    do with mdins.
    """
    return np.array(
        [
            (i / supercell[0], j / supercell[1], k / supercell[2])
            for i in range(supercell[0])
            for j in range(supercell[1])
            for k in range(supercell[2])
        ]
    )


def harmonic_modes(primitive: Atoms, supercell: tuple[int, int, int], cache: str):
    """Phonon modes on the commensurate grid, via ASE finite displacement and Euphonic.

    ASE supplies the force constants; Euphonic does the physics that matters here —
    building the dynamical matrix, applying the acoustic sum rule and diagonalising.
    """
    from ase.phonons import Phonons
    from euphonic import Crystal, ForceConstants, ureg

    phonons = Phonons(
        primitive, lennard_jones(), supercell=supercell, delta=0.01, name=cache
    )
    phonons.run()
    phonons.read(acoustic=True)

    crystal = Crystal(
        np.array(primitive.cell) * ureg("angstrom"),
        primitive.get_scaled_positions(),
        np.array(primitive.get_chemical_symbols()),
        primitive.get_masses() * ureg("amu"),
    )
    force_constants = ForceConstants(
        crystal,
        phonons.get_force_constant() * ureg("eV/angstrom**2"),
        np.diag(supercell),
        phonons.compute_lattice_vectors().T,
    )
    return force_constants.calculate_qpoint_phonon_modes(
        commensurate_grid(supercell), asr="reciprocal"
    )


def reference_pdos(modes, primitive: Atoms) -> dict[str, tuple[NDArray, NDArray]]:
    """Species-projected harmonic pDOS, as a weighted list of modes.

    Built from the eigenvectors rather than from :meth:`calculate_pdos` for one reason:
    the three acoustic modes at Γ have to be dropped. They are rigid translation of the
    whole cell, which ``remove_com_velocity`` projects out of the MD, so leaving them in
    the reference compares a spectrum that has them against one that does not.

    Returns:
        Species to ``(frequencies, weights)``, both 1-D over the retained modes. The
        weight of atom ``i`` in mode ``s`` is ``|e_is|²`` summed over the three
        Cartesian components.

    The velocity spectral weight of an atom is really ``|e_is|²·k_BT/m_i``, and the
    ``1/m_i`` is *not* included here. Within one species it is a constant that divides
    out of any normalised quantity, which is all this harness computes — but it means
    the two species' arrays are not on a common scale. Summing them to build a total DOS
    would over-weight krypton by the mass ratio. Normalise per species, or restore the
    factor, before composing them.
    """
    frequencies = modes.frequencies.to("meV").magnitude
    per_atom = np.sum(np.abs(modes.eigenvectors) ** 2, axis=-1)
    symbols = np.array(primitive.get_chemical_symbols())

    # Γ acoustic modes come back as ~0 with either sign, hence the absolute value.
    keep = np.abs(frequencies) > 1e-3
    return {
        species: (
            frequencies[keep],
            per_atom[..., symbols == species].sum(axis=-1)[keep],
        )
        for species in dict.fromkeys(symbols)
    }


def acoustic_weight_fraction(modes, primitive: Atoms) -> dict[str, float]:
    """Share of each species' spectral weight sitting in the Γ acoustic modes.

    Those eigenvectors go as ``√m``, so a heavy species carries proportionally more of
    the translation that gets projected out.
    """
    frequencies = modes.frequencies.to("meV").magnitude
    per_atom = np.sum(np.abs(modes.eigenvectors) ** 2, axis=-1)
    symbols = np.array(primitive.get_chemical_symbols())
    acoustic = np.abs(frequencies) <= 1e-3

    return {
        species: float(
            per_atom[acoustic][..., symbols == species].sum()
            / per_atom[..., symbols == species].sum()
        )
        for species in dict.fromkeys(symbols)
    }


def md_trajectory(
    primitive: Atoms,
    supercell: tuple[int, int, int],
    *,
    seed: int = 0,
    n_frames: int = N_FRAMES,
) -> VelocityTrajectory:
    """NVE molecular dynamics on the crystal, as an mdins trajectory.

    Started at twice the target temperature because half the kinetic energy goes into
    potential energy as the system equilibrates.

    Separate from :func:`run_nve` so that two estimators can be run over the *same*
    velocities. Comparing estimators across separate trajectories would fold the
    run-to-run scatter into the comparison and swamp the thing being measured.
    """
    from ase import units as ase_units
    from ase.md.velocitydistribution import MaxwellBoltzmannDistribution
    from ase.md.verlet import VelocityVerlet

    atoms = primitive * supercell
    atoms.calc = lennard_jones()

    rng = np.random.default_rng(seed)
    MaxwellBoltzmannDistribution(atoms, temperature_K=2 * TEMPERATURE, rng=rng)
    dynamics = VelocityVerlet(atoms, timestep=TIMESTEP_FS * ase_units.fs)
    dynamics.run(500)  # let the initial condition forget itself

    velocities = np.empty((n_frames, len(atoms), 3))
    for frame in range(n_frames):
        dynamics.run(DUMP_EVERY)
        velocities[frame] = atoms.get_velocities() * ase_units.fs * 1e3

    return VelocityTrajectory(
        velocities=velocities,
        masses=atoms.get_masses(),
        symbols=atoms.get_chemical_symbols(),
        dt=DUMP_EVERY * TIMESTEP_FS * 1e-3,
        provenance=Provenance(source="ase-lj-nve"),
    ).remove_com_velocity()


def estimate(trajectory: VelocityTrajectory, **kwargs) -> VelocitySpectralDensity:
    """Run stage B over a trajectory on the settings the whole of M2 shares.

    Args:
        trajectory: From :func:`md_trajectory`.
        **kwargs: Override any of the defaults — in particular ``estimator="vacf"``,
            which is how the two routes are compared on identical input.
    """
    settings: dict = {
        "e_max": 20.0,
        "n_bins": 400,
        "segment_length": SEGMENT_LENGTH,
        "temperature": trajectory.temperature(),
        "ensemble": "NVE",
    }
    settings.update(kwargs)
    return velocity_spectral_density(trajectory, **settings)


def run_nve(
    primitive: Atoms,
    supercell: tuple[int, int, int],
    *,
    seed: int = 0,
    n_frames: int = N_FRAMES,
) -> VelocitySpectralDensity:
    """Molecular dynamics and the Welch spectral density in one call."""
    return estimate(md_trajectory(primitive, supercell, seed=seed, n_frames=n_frames))


# -- comparison statistics --------------------------------------------------------


def moment(energies: NDArray, weight: NDArray, order: int) -> float:
    """Normalised moment of a weighted spectrum."""
    return float(np.sum(weight * energies**order) / np.sum(weight))


def moment_uncertainty(
    energies: NDArray, weight: NDArray, error: NDArray, order: int
) -> float:
    """Standard error of a moment, propagated from the per-bin Welch spread.

    The derivative of a normalised moment with respect to one bin's weight is
    ``(E^n - <E^n>) / Σw``, so bins near the mean contribute almost nothing and the band
    edges dominate.

    **This is not the uncertainty the tests use, and on its own it is badly wrong.** It
    measures the scatter between Welch segments of a *single* trajectory, which in a
    cold NVE crystal is nearly blind to the thing that actually moves the moments. The
    normal-mode energies are constants of motion fixed by the initial Maxwell-Boltzmann
    draw, so every segment of one run sees the same occupation of the same modes and
    this number reports only phase and leakage noise at fixed occupation. Measured
    against the run-to-run spread over :data:`SEEDS` it is too small by about a factor
    of four. It is kept because it is the right diagnostic for *within-run* convergence
    and because the figures quote it as such; the tolerances come from
    :func:`ensemble_moment`.
    """
    centred = energies**order - moment(energies, weight, order)
    return float(np.sqrt(np.sum((error * centred) ** 2)) / np.sum(weight))


def species_weight(
    density: VelocitySpectralDensity, species: str
) -> tuple[NDArray, NDArray]:
    """Normalised pDOS of one species and its standard error.

    Per-atom errors are summed linearly rather than in quadrature, which is why this
    does not simply read :meth:`SpectralDensity.group_by_species`. Atoms of a species
    all sample the same modes, so their segment-to-segment fluctuations move together;
    treating them as independent shrinks the error bar by ``√N`` and would make the
    tolerances tighter than the data can justify.
    """
    index = [i for i, symbol in enumerate(density.symbols) if symbol == species]
    pdos = density.pdos()[index].sum(axis=0)
    error = density.pdos_std[index].sum(axis=0)
    total = pdos.sum()
    return pdos / total, error / total


# -- the ensemble -----------------------------------------------------------------
#
# Everything above describes one trajectory. One trajectory is not enough, for a reason
# that took a while to see and that is worth stating at length, because the obvious
# error bar is the wrong one and it is wrong by a large factor.
#
# These runs are NVE on a crystal that is very nearly harmonic. In a harmonic system the
# energy of each normal mode is a constant of motion: whatever the initial
# Maxwell-Boltzmann draw happens to put into mode s stays in mode s for the whole run.
# The pDOS weight of a mode is proportional to that energy, so the measured spectrum is
# not the equilibrium spectrum — it is one draw from it, frozen at t=0 and held there.
#
# Two consequences follow, and they are the opposite of the intuition:
#
# 1. Running longer does not help. The draw never re-randomises, so the moments converge
#    to a seed-dependent value rather than to the harmonic one.
# 2. The inter-segment spread that ``velocity_spectral_density`` reports cannot see any
#    of this, because every segment of one trajectory shares the same draw. It reports
#    phase and leakage noise at fixed occupation, and comes out about four times too
#    small.
#
# Measured here, single-species, six seeds: the first moment scatters by 3.7%, against a
# propagated within-run error of 1.0%. Seeds 0 and 2 sit at the same temperature to
# within 0.1 K and differ by six of those propagated sigmas.
#
# The fix is to average over independent draws and take the error bar from the scatter
# between them. That is a measured sampling distribution rather than a modelled one, so
# it needs no assumption about which bins or which atoms are correlated — the questions
# that made the propagated version delicate. It costs one MD run per seed.

#: Independent initial draws. The standard error on the ensemble mean falls as ``1/√n``
#: while the cost rises as ``n``, so the number is set by how sharp the test needs to
#: be. Ten gives about 1.2% on the single-species first moment, which makes the
#: three-sigma threshold reject a frequency-axis error of roughly 3.5% — comfortably
#: inside the 5% used by the negative control, and far inside any plausible unit slip.
#: Six seeds would leave the control passing by only a quarter of its threshold.
SEEDS = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)


def ensemble(
    primitive: Atoms,
    supercell: tuple[int, int, int],
    *,
    seeds: Sequence[int] = SEEDS,
    n_frames: int = N_FRAMES,
) -> list[VelocitySpectralDensity]:
    """One spectral density per independent initial draw."""
    return [
        run_nve(primitive, supercell, seed=seed, n_frames=n_frames) for seed in seeds
    ]


def ensemble_moment(
    densities: Sequence[VelocitySpectralDensity],
    order: int,
    *,
    species: str | None = None,
    limit: float | None = None,
) -> tuple[float, float]:
    """Mean and standard error of a spectral moment across the ensemble.

    The moment is computed independently for each run and the spread is taken over
    those, so the error bar is the sampling distribution of the statistic itself.

    Args:
        densities: The ensemble, as returned by :func:`ensemble`.
        order: Moment order; 1 for the mean energy, 2 for the mean square.
        species: Project onto one species first. ``None`` uses the whole system.
        limit: Discard weight above this energy in meV, to keep the ``E^n`` weighting
            from being dominated by the small leakage tail above the harmonic band.

    Returns:
        ``(mean, standard_error_of_the_mean)``, both in meV to the given power.
    """
    values = []
    for density in densities:
        energies = density.frequencies
        if species is None:
            weight = density.total_pdos()
        else:
            weight, _ = species_weight(density, species)
        inside = slice(None) if limit is None else energies <= limit
        values.append(moment(energies[inside], weight[inside], order))

    sample = np.array(values)
    return float(sample.mean()), float(sample.std(ddof=1) / np.sqrt(len(sample)))


def ensemble_species_weight(
    densities: Sequence[VelocitySpectralDensity], species: str
) -> tuple[NDArray, NDArray]:
    """Ensemble-mean normalised pDOS of one species, and its standard error per bin.

    The per-bin error here is again the run-to-run scatter, not the within-run Welch
    spread, so the shaded band in the figures means the same thing as the error bars on
    the moments.
    """
    stack = np.array([species_weight(density, species)[0] for density in densities])
    return stack.mean(axis=0), stack.std(axis=0, ddof=1) / np.sqrt(len(stack))
